services:
  - type: web
    name: ankit-academy-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
